// Mocks generated by Mockito 5.4.4 from annotations
// in robin_ai/test/data/datasources/mcp/tool_executor_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:robin_ai/data/datasources/mcp/mcp_client.dart' as _i2;
import 'package:robin_ai/data/model/mcp_server_config.dart' as _i5;
import 'package:robin_ai/domain/entities/mcp_tool.dart' as _i6;
import 'package:robin_ai/presentation/config/services/mcp_server_service.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeMcpClient_0 extends _i1.SmartFake implements _i2.McpClient {
  _FakeMcpClient_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [McpServerService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMcpServerService extends _i1.Mock implements _i3.McpServerService {
  MockMcpServerService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> saveServerConfig(_i5.McpServerConfig? config) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveServerConfig,
          [config],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i5.McpServerConfig>> getAllServers() => (super.noSuchMethod(
        Invocation.method(
          #getAllServers,
          [],
        ),
        returnValue: _i4.Future<List<_i5.McpServerConfig>>.value(
            <_i5.McpServerConfig>[]),
      ) as _i4.Future<List<_i5.McpServerConfig>>);

  @override
  _i4.Future<void> deleteServer(String? serverId) => (super.noSuchMethod(
        Invocation.method(
          #deleteServer,
          [serverId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<bool> testConnection(_i5.McpServerConfig? config) =>
      (super.noSuchMethod(
        Invocation.method(
          #testConnection,
          [config],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i2.McpClient getClient(_i5.McpServerConfig? config) => (super.noSuchMethod(
        Invocation.method(
          #getClient,
          [config],
        ),
        returnValue: _FakeMcpClient_0(
          this,
          Invocation.method(
            #getClient,
            [config],
          ),
        ),
      ) as _i2.McpClient);

  @override
  _i4.Future<List<_i6.McpTool>> getAvailableTools() => (super.noSuchMethod(
        Invocation.method(
          #getAvailableTools,
          [],
        ),
        returnValue: _i4.Future<List<_i6.McpTool>>.value(<_i6.McpTool>[]),
      ) as _i4.Future<List<_i6.McpTool>>);

  @override
  _i4.Future<Map<String, dynamic>> executeTool(
    String? toolName,
    Map<String, dynamic>? arguments,
    String? serverId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #executeTool,
          [
            toolName,
            arguments,
            serverId,
          ],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
